# Generated by Django 4.2.6 on 2023-10-20 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dono', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=120)),
                ('nome_animal', models.CharField(max_length=120)),
                ('raca', models.CharField(max_length=120)),
                ('caracteristicas', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
