# Generated by Django 4.2.6 on 2023-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicho',
            name='caracteristicas',
            field=models.CharField(max_length=10000),
        ),
    ]
