# Generated by Django 4.2.6 on 2023-10-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_bicho_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicho',
            name='caracteristicas',
            field=models.CharField(max_length=1000),
        ),
    ]
